"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { DOMAIN_META, type Domain } from "@/lib/domain";
export function NewCardForm({domain,disabled}:{domain:Domain;disabled?:boolean}){
 const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const meta=DOMAIN_META[domain];
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); if(disabled)return; setBusy(true); setError(""); const fd=new FormData(e.currentTarget); const body:Record<string,string|number|null>={name:String(fd.get("name")||""),domain,cardNumber:fd.get("cardNumber")?String(fd.get("cardNumber")):null,setName:fd.get("setName")?String(fd.get("setName")):null,year:fd.get("year")?Number(fd.get("year")):null,variant:fd.get("variant")?String(fd.get("variant")):null,copyLabel:fd.get("copyLabel")?String(fd.get("copyLabel")):"1 of 1",rawLow:fd.get("rawLow")?Number(fd.get("rawLow")):null,rawHigh:fd.get("rawHigh")?Number(fd.get("rawHigh")):null,rawMid:fd.get("rawMid")?Number(fd.get("rawMid")):null,notes:fd.get("notes")?String(fd.get("notes")):null}; try{const res=await fetch('/api/cards',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); if(!res.ok)throw new Error(await res.text()); const data=await res.json(); router.push(`/${domain}/cards/${data.id}`);}catch(err){setError(err instanceof Error?err.message:'Failed');setBusy(false)}}
 return <form className="card" onSubmit={submit}><div className="card-head"><div className="card-title">Physical card · {meta.label}</div></div><div className="card-body grid" style={{gap:12}}>
  <label><div className="grade-label" style={{marginBottom:6}}>{meta.nameFieldLabel}</div><input className="input" style={{width:'100%'}} name="name" required disabled={disabled}/></label>
  <div className="upload-grid"><label><div className="grade-label" style={{marginBottom:6}}>Card number</div><input className="input" style={{width:'100%'}} name="cardNumber" placeholder={meta.numberPlaceholder}/></label><label><div className="grade-label" style={{marginBottom:6}}>Set</div><input className="input" style={{width:'100%'}} name="setName" placeholder={meta.setPlaceholder}/></label></div>
  <div className="upload-grid"><label><div className="grade-label" style={{marginBottom:6}}>Variant / printing</div><input className="input" style={{width:'100%'}} name="variant" placeholder={meta.variantPlaceholder}/></label><label><div className="grade-label" style={{marginBottom:6}}>Copy label</div><input className="input" style={{width:'100%'}} name="copyLabel" defaultValue="1 of 1"/></label></div>
  <div className="upload-grid"><label><div className="grade-label" style={{marginBottom:6}}>Year</div><input className="input" style={{width:'100%'}} name="year" type="number"/></label><label><div className="grade-label" style={{marginBottom:6}}>Raw midpoint</div><input className="input" style={{width:'100%'}} name="rawMid" type="number" step="0.01"/></label></div>
  <div className="upload-grid"><label><div className="grade-label" style={{marginBottom:6}}>Raw low</div><input className="input" style={{width:'100%'}} name="rawLow" type="number" step="0.01"/></label><label><div className="grade-label" style={{marginBottom:6}}>Raw high</div><input className="input" style={{width:'100%'}} name="rawHigh" type="number" step="0.01"/></label></div>
  <label><div className="grade-label" style={{marginBottom:6}}>Notes</div><textarea className="input" style={{width:'100%',minHeight:90}} name="notes"/></label>
  {disabled&&<div className="callout">Connect the database first. Demo mode is read-only.</div>}{error&&<div className="callout">{error}</div>}
  <button className="btn primary" disabled={disabled||busy}>{busy?'Saving…':'Create card & add media'}</button>
 </div></form>
}
